name: Refresh Finsight data

on:
    workflow_dispatch:
    schedule:
      - cron: '0 3 * * *'

 jobs:
    refresh:
      runs-on: ubuntu-latest
      steps:
        - name: Refresh critical transactions
          run: curl -X GET https://mbrvhaftlidajvuxhjtb.functions.supabase.co/cron-refresh-critical-transactions
        - name: Refresh insights
          run: curl -X GET https://mbrvhaftlidajvuxhjtb.functions.supabase.co/make-server-d84f5a52/insights/generate
