name: Refresh Finsight data
  on:
    schedule:
      - cron: '0 3 * * *' # runs every night at 3â€¯AM UTC
  jobs:
    refresh:
      runs-on: ubuntu-latest
      steps:
        - name: Refresh critical transactions
          run: curl -X GET https://mbrvhaftlidajvuxhjtb.functions.supabase.co/cron-refresh-critical-transactions
        - name: Refresh insights
          run: curl -X GET https://mbrvhaftlidajvuxhjtb.functions.supabase.co/make-server-d84f5a52/insights/generate